Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using Day2.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Day2.Models.Instructors;
using AutoMapper;

namespace Day2.Controllers
{
    public class InstructorController : Controller
    {
        Context context=new Context();
        private readonly IMapper _mapper;

        public InstructorController( IMapper mapper)
        {
            _mapper = mapper;
        }
        public IActionResult Index()
        {

            return View("Index",context.Instructors.ToList());
        }

        public IActionResult InstructorDetails(int id)
        {

            Instructor? instructor = context.Instructors.Include(i=>i.Department).Include(i=>i.Course).FirstOrDefault(inst =>inst.Id == id);

            if(instructor==null)
            {
                return View("PageNotFound");
            }
            else
            {
                return View("InstructorDetails",instructor);
            }
           

        }

        public IActionResult AddNewInstructor()
        {

            ViewBag.Departments = context.Departments.ToList();
            ViewBag.Courses = context.Courses.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult InsertInstructor(InstructorCreateDTO inst )
        {


            //Instructor instructor = new Instructor();

            if (inst.Name == null || inst.Name.Trim() == String.Empty || inst.Address == null || inst.Address.Trim() == string.Empty || inst.ImageFile == null)
            {
                ViewBag.Departments = context.Departments.ToList();
                ViewBag.Courses = context.Courses.ToList();
                return View("AddNewInstructor", inst);
            }

            string fullPath = Path.Combine(Constants.INSTRUCTORS_IMAGES_PATH, inst.ImageFile.FileName);
            // set instructor image with image name
            //inst.Image = inst.Image.FileName; 

            // write image in wwwroot/image/instructors
            inst.ImageFile.CopyTo(new FileStream(fullPath, FileMode.Create));
            inst.Image = inst.ImageFile.FileName;
           
            var instructor = _mapper.Map<InstructorCreateDTO, Instructor>(inst);
            context.Instructors.Add(instructor);
            // save instructor  in database
            context.SaveChanges();
            // back to index view
            return View("Index", context.Instructors.ToList());

        }

      
        public IActionResult UpdateInstructor(int id)
        {
         
            Instructor? instructor = context.Instructors.ToList().FirstOrDefault(inst => inst.Id == id);
            if(instructor==null)
                return View("PageNotFound");



            ViewBag.Departments = context.Departments.ToList();
            ViewBag.Courses = context.Courses.ToList();
            return View(instructor);
        }

        [HttpPost]
        public IActionResult UpdateInstructoreData(Instructor inst)
        {

            ViewBag.Departments = context.Departments.ToList();
            ViewBag.Courses = context.Courses.ToList();

            if (inst.Name == null || inst.Name.Trim() == String.Empty || inst.Address == null || inst.Address.Trim() == string.Empty || inst.Image == null || inst.Image.Trim() == string.Empty)
            {
              
                return View("UpdateInstructor", inst);
            }
          
            Instructor? instructor = context.Instructors.FirstOrDefault(ins => ins.Id == inst.Id);

            // redirect to page not found if instructor is not found
            if (instructor == null)
                return View("PageNotFound");


            // update Instructor

            instructor.Name = inst.Name;
            instructor.Salary = inst.Salary;
            instructor.Address = inst.Address;
            instructor.Image = inst.Image;
            instructor.Dept_Id = inst.Dept_Id;
            instructor.Course_Id = inst.Course_Id;
            context.SaveChanges();
            return View("Index", context.Instructors.ToList());
        }


    }
}

Controllers/TraineeController.cs
using Microsoft.AspNetCore.Mvc;
using Day2.Models;
using Day2.ViewModels;
using Microsoft.EntityFrameworkCore;
namespace Day2.Controllers
{
    public class TraineeController : Controller
    {
       Context context=new Context();
      
        public IActionResult Index()
        {
            IEnumerable<Trainee> trainees = context.Trainees.Select(tra=>tra).Include(tra=>tra.Department);

            return View(trainees);
        }

        public IActionResult TraineeResult (int Id)
        {

            Trainee? trainee=context.Trainees.Include(tra => tra.courseResults).FirstOrDefault(train => train.Id == Id);
            
            if(trainee==null)
                return View("PageNotFound");

            TraineeViewModel traineeViewModel = new TraineeViewModel();
            traineeViewModel.TraineeName = trainee.Name;
            traineeViewModel.ID = trainee.Id;
            traineeViewModel.Image = trainee.Image;
            List<TraineeCourseViewModel> results=new List<TraineeCourseViewModel>();    

            foreach(CourseResult courseResult in trainee.courseResults)
            {
                Course? course = context.Courses.FirstOrDefault(crs => crs.Id == courseResult.Course_Id);

                if (course == null)
                    continue;

                results.Add(
                    new TraineeCourseViewModel()
                    {
                        CourseName = course.Name,
                        CourseDegree = courseResult.Degree,
                        color = (courseResult.Degree - course.MinDegree) < 0 ? "text-danger" : "text-success",
                        State = (courseResult.Degree - course.MinDegree) <0?State.Faild:State.Pass

                    });
            }

            traineeViewModel.TraineeResults = results;
            
            return View(traineeViewModel);
        }

        // this action to add new trainee

        public IActionResult AddNewTrainee()
        {
            return View(context.Departments.ToList());


        }

        [HttpPost]
        public IActionResult InsertTrainee(Trainee trainee, IFormFile Image)
        {

            if(trainee.Name==null|| trainee.Name.Trim()==String.Empty|| trainee.Address == null || trainee.Address.Trim() == String.Empty || Image == null)
            {
                ViewBag.Trainee = trainee;
                return RedirectToAction("AddNewTrainee", context.Departments.ToList());
            }

            // creating full path
            // Combine Fullpath with filename
            string fullPath = Path.Combine(Constants.TRAINEE_IMAGES_PATH, Image.FileName);
            // set Trainee image with image name
            trainee.Image = Image.FileName;

            // write image in wwwroot/image/Trainees
            Image.CopyTo(new FileStream(fullPath, FileMode.Create));
            // add Trainee in Trainees collection
            context.Trainees.Add(trainee);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/PageNotFound.cshtml
<h1 class="text-center text-danger">Page Not Found</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Day2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Day2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light  border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ITI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trainee" asp-action="Index">Trainees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Day2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet"  href='~/lib/bootstrap/dist/css/bootstrap.min.css'/>
    <link rel="stylesheet" href='~/css/site.css'/>
</head>
<body>
    
    <header >
        <nav class="navbar navbar-expand-lg navbar-dark container sticky-top ">
              <a class="navbar-brand" asp-action='index' asp-controller='Home' >ITI</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" asp-action='index' asp-controller='Home'>Home <span class="sr-only"></span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" asp-action='index' asp-controller='Instructor'>Instructors</a>
                  </li>
                 
                  <li class="nav-item">
                    <a class="nav-link " asp-action='index' asp-controller='Trainee'>Trainees</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link " asp-action='index' asp-controller='Course'>Courses</a>
                  </li>
                </ul>
                <form class="form-inline my-2 ms-auto">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" style='width:fit-content;display:inline-block'>
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
              </div>
        </nav>
    </header>
    <main class='my-4'>
        <div class='container'>@RenderBody()</div>
    </main>
    <footer class='p-4 text-center'>all rights &copy; 2022 Ahmed Alaa</footer>
    <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" ></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
     @await RenderSectionAsync("Scripts", required: false)
</body>
</html>